Spring Security configuration
julia-shvabovich/cinema pull request #12
Opened 2020-10-29 10:38 UTC by julia-shvabovich

2020-10-29 10:45 UTC, andromash reviewed
good job!

2020-10-29 10:45 UTC, andromash commented on src/main/java/cinema/config/SecurityConfig.java
> +                .withUser("user").password(getEncoder().encode("123")).roles("USER");
You have constraint that password should be at least 4 chars. Maybe this works, but it makes no sense

2020-10-29 12:51 UTC, KseniiaMakarova requested changes
- have you tested your email/password validation? I see that something is missing for it to work
- let's add validation of other RequestDtos?
- remove HashUtil

2020-10-29 12:51 UTC, KseniiaMakarova commented on src/main/java/cinema/Main.java
maybe let's remove this whole class?

2020-10-29 12:51 UTC, KseniiaMakarova commented on src/main/java/cinema/controller/ShoppingCartController.java
>                                  @RequestBody MovieSessionRequestDto movieSession) {
maybe let's pass movieSessionId as a @RequestParam?

2020-10-29 14:38 UTC, julia-shvabovich commented on src/main/java/cinema/Main.java
done

2020-10-29 14:48 UTC, julia-shvabovich commented on src/main/java/cinema/controller/ShoppingCartController.java
>                                  @RequestBody MovieSessionRequestDto movieSession) {
done

2020-10-29 16:09 UTC, KseniiaMakarova requested changes

2020-10-29 16:09 UTC, KseniiaMakarova commented on src/main/java/cinema/service/MovieSessionService.java
> +    Optional<MovieSession> findById(Long id);
let's return MovieSession here?

2020-10-29 16:09 UTC, KseniiaMakarova commented on src/main/java/cinema/model/dto/cinemahall/CinemaHallRequestDto.java
> +    @Min(5)
does it work without @Valid?

2020-11-02 14:46 UTC, julia-shvabovich commented on src/main/java/cinema/service/MovieSessionService.java
> +    Optional<MovieSession> findById(Long id);
done

2020-11-02 16:53 UTC, Sofasmile commented on src/main/java/cinema/validation/PasswordMatchValidator.java
> +        return password.equals(passwordRepeated);
```suggestion
        return Objects.equals(password, passwordRepeated);
```

2020-11-02 16:53 UTC, Sofasmile commented on src/main/java/cinema/model/dto/movie/MovieRequestDto.java
> +    @NotNull
ця анотація не буде працювати адже в методі контроллера немає анотації Valid
перевір решту дто

2020-11-02 20:34 UTC, julia-shvabovich commented on src/main/java/cinema/model/dto/movie/MovieRequestDto.java
> +    @NotNull
done

2020-11-03 09:49 UTC, Sofasmile commented on src/main/java/cinema/model/dto/user/UserRequestDto.java
> +    @Email
це не наша кастомна анотація) Зверни увагу на імпорт і порівняй його з FieldsValueMatch

2020-11-03 09:55 UTC, julia-shvabovich commented on src/main/java/cinema/model/dto/user/UserRequestDto.java
> +    @Email
done...

2020-11-03 09:56 UTC, Sofasmile approved these changes

2020-11-03 09:57 UTC, merged