hb-06
julia-shvabovich/cinema pull request #4
Opened 2020-10-08 19:01 UTC by julia-shvabovich

2020-10-08 22:16 UTC, DariiaPikul requested changes

2020-10-08 22:16 UTC, DariiaPikul commented on src/main/java/cinema/Main.java
> +        shoppingCartService.addSession(movieSession, testUser);
How about using all of the service methods?

2020-10-08 22:16 UTC, DariiaPikul commented on src/main/java/cinema/dao/impl/ShoppingCartDaoImpl.java
> +    public ShoppingCart getByUser(User user) {
Let's return an Optional from the DAO layer

2020-10-08 22:16 UTC, DariiaPikul commented on src/main/java/cinema/model/ShoppingCart.java
> +    }
You're passing your entities to the exceptions' messages.
How do we know the entity details since we don't have the toString() overridden?

2020-10-08 22:16 UTC, DariiaPikul commented on src/main/java/cinema/service/impl/ShoppingCartServiceImpl.java
> +    TicketDao ticketDao;
Access modifiers

2020-10-08 22:16 UTC, DariiaPikul commented on src/main/java/cinema/service/impl/ShoppingCartServiceImpl.java
> +    public void registerNewShoppingCart(User user) {
How about using this method in the AuthenticationService?

2020-10-09 07:03 UTC, julia-shvabovich commented on src/main/java/cinema/service/impl/ShoppingCartServiceImpl.java
> +    TicketDao ticketDao;
no comments...

2020-10-09 07:14 UTC, Sofasmile commented on src/main/java/cinema/dao/impl/ShoppingCartDaoImpl.java
> +    public ShoppingCart getByUser(User user) {
@DariiaPikul в даному випадку це не є обов'язковим повертати Optional

2020-10-09 07:14 UTC, Sofasmile commented on src/main/java/cinema/model/ShoppingCart.java
> +    @OneToOne
чому ти вирішила не використовувати тут MapsId?

2020-10-09 07:33 UTC, julia-shvabovich commented on src/main/java/cinema/model/ShoppingCart.java
> +    @OneToOne
done

2020-10-09 13:51 UTC, Sofasmile approved these changes

2020-10-12 14:17 UTC, merged